"""Body-runtime compatibility facade for PACT work contracts.

The body keeps importing this module for now. Core PACT contract definitions,
classification, evidence modeling, and evaluation live in ``pact_engine`` so
the runtime-facing API can move independently from body compatibility shims.
"""

from __future__ import annotations

try:
    from .pact_engine import (
        ActivationContext,
        ContractDefinition,
        EvidenceEntry,
        EvidenceLedger,
        EvidenceView,
        EvaluationResult,
        ExecutionError,
        ExecutionState,
        Objective,
        PactEvaluator,
        Plan,
        ProposedOutcome,
        RecoveryState,
        StepRecord,
        ToolObservation,
        WorkContract,
        build_contract,
        classify_activation,
        classify_work,
        contract_definition,
        contract_prompt,
        extract_urls,
        format_blocked_completion,
        list_contract_kinds,
        validate_completion,
    )
except ImportError:  # pragma: no cover - runtime imports this as a top-level module.
    from pact_engine import (
        ActivationContext,
        ContractDefinition,
        EvidenceEntry,
        EvidenceLedger,
        EvidenceView,
        EvaluationResult,
        ExecutionError,
        ExecutionState,
        Objective,
        PactEvaluator,
        Plan,
        ProposedOutcome,
        RecoveryState,
        StepRecord,
        ToolObservation,
        WorkContract,
        build_contract,
        classify_activation,
        classify_work,
        contract_definition,
        contract_prompt,
        extract_urls,
        format_blocked_completion,
        list_contract_kinds,
        validate_completion,
    )

__all__ = [
    "ActivationContext",
    "ContractDefinition",
    "EvidenceEntry",
    "EvidenceLedger",
    "EvidenceView",
    "EvaluationResult",
    "ExecutionError",
    "ExecutionState",
    "Objective",
    "PactEvaluator",
    "Plan",
    "ProposedOutcome",
    "RecoveryState",
    "StepRecord",
    "ToolObservation",
    "WorkContract",
    "build_contract",
    "classify_activation",
    "classify_work",
    "contract_definition",
    "contract_prompt",
    "extract_urls",
    "format_blocked_completion",
    "list_contract_kinds",
    "validate_completion",
]
