FROM ollama/ollama:0.9.3

ARG BUILD_ID=unknown
ARG SOURCE_HASH=unknown

LABEL agency.build.id="${BUILD_ID}"
LABEL agency.source.hash="${SOURCE_HASH}"
LABEL org.opencontainers.image.source="https://github.com/geoffbelknap/agency"
LABEL org.opencontainers.image.description="Agency embeddings runtime based on Ollama"
